### ISSUE TITLE
with proxy_connect i cannot intercept errors with error_page

### ISSUE THREAD

**Issue by hbvenancio** [chobits/ngx_http_proxy_connect_module#108]
Hi,
first of all congratulations for the module!

I have built and installed it successfully (on linux). It works fine as a forward-proxy but it seems i cannot _proxy_intecept_errors_.
I am able to "intercept" the requests passing through nginx but not the responses and rewriting them. In the below example i am trying to intercept the 401 HTTP code and rewrite it to 302, but seems i am not able to intercept errors ?

    server \{
        listen 8755;
        proxy_connect;
        location / \{
          proxy_pass https://intrauat.web.bc;

          proxy_intercept_errors on;
          error_page 401 = @rewrite_401;
        }

        location @rewrite_401 \{
          return 302 https://intrauat.web.bc/login;
        }
     }

I am not sure whether this is by-design, a bug, or even a feature not yet implemented.

Could you please help me understanding ?

Many thanks in advance.
BR,
Hugo

**Comment by chobits** [comment]
The proxy_connect module works instead of proxy module (e.g. proxy_pass directive), this module only proxied backend raw stream to client. However, proxy_intercept_erros only works for proxy module.

More detail and why it cannot intercept the proxied backend raw stream, see :
*What functions does this module implement: https://github.com/chobits/ngx_http_proxy_connect_module/issues/78
* difference between proxy_connect module with proxy module: https://github.com/chobits/ngx_http_proxy_connect_module/issues/84

**Comment by chobits** [comment]
ping? think it rresolved, feel free to reopen if you still have any problem

**Comment by hbvenancio** [comment]
Hi,
I understand this is not yet implemented but don't you think it would be a
good idea?

Br
Hugo

**Comment by chobits** [comment]
hi @hbvenancio 

> I understand this is not yet implemented but don't you think it would be a good idea?

Not easy to implemented, see my comment https://github.com/chobits/ngx_http_proxy_connect_module/issues/108#issuecomment-498964963.

This module is designed to proxy raw stream directly without parsing and modification.
