### ISSUE TITLE
Websocket connection timesout after few seconds

### ISSUE THREAD

**Issue by andkuha** [chobits/ngx_http_proxy_connect_module#122]
After establishing connection its timeouts within 20 sec
2019/08/07 11:17:59 [error] 6#0: *6 upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect), client: 10.0.0.1, server: websocket.my.com, request: "CONNECT websocket.my.com:443 HTTP/1.0"

**Comment by chobits** [comment]
Use latest master branch, I have updated error log to dispart connect/read upstream error and show backend address.

BTW, also show details about:
* proxy_conf configuration (proxy_connect_* directive)
* debug log: http://nginx.org/en/docs/debugging_log.html

> upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect)

This means proxy_connect module tries to establish tcp connection with backend server, but failed because connection timeout.

**Comment by andkuha** [comment]
It was misconfiguration, closing this
