### ISSUE TITLE
Unable to proxy HTTPS requests to local static files

### ISSUE THREAD

**Issue by loory** [chobits/ngx_http_proxy_connect_module#123]
Our original requirement was to proxy some HTTPS requests to local static files, but after testing, the configuration local location rule was invalid.
Does this module support configuring location rules to map local directories?
Use environment: nginx 1.14.2 + rewrite path

**Comment by chobits** [comment]
> Does this module support configuring location rules to map local directories?

No. Because:
  1.  The CONNECT request does not include URI. This request only tells proxy_connect module where the backend server is (backend server host or ip address).
  2. The raw stream, which is proxied in the CONNECT tunnel, will not be parsed.

Note that this module is used to create  4-layer TCP tunnel, there is no way to get someting about 7 layer information.
