### ISSUE TITLE
Able to use proxy_ssl_name

### ISSUE THREAD

**Issue by deba12** [chobits/ngx_http_proxy_connect_module#180]
## Why you need it?

We have complicated forward->reverse proxy setup. (our upstream is the same nginx listening on different port)
Our need is to able to set sni hostname before connect, just like proxy_ssl_name works

Thanks

**Comment by chobits** [comment]
hi @deba12 

See followint stream:

```
client - [http/https protocol]---> nginx: proxy_connect_module --- [ tcp protocol] ----> upstream
```

For interactiion between proxy_connect_module and upstream, we cannot control the real data flow in `[tcp protocol]`, proxy_connect_module just tries to connect upstream and proxy the raw data flow.

**Comment by chobits** [comment]
QUATe from project FAQ：this module cannot parse or operate data flow between nginx and upstream: https://github.com/chobits/ngx_http_proxy_connect_module/issues/123#issuecomment-520668898.

**Comment by deba12** [comment]
Hi @chobits 
https://github.com/chobits/ngx_http_proxy_connect_module/blob/cb4dcd53310afa481449808afb6834eec1303573/ngx_http_proxy_connect_module.c#L1535
Here on this line you module sets up sni name, when making ssl connection to upstream server. 
It will be very good to be able to change sni name just as we are able to change connect address with _proxy_connect_address_

**Comment by chobits** [comment]
hi @deba12 

https://github.com/chobits/ngx_http_proxy_connect_module/blob/cb4dcd53310afa481449808afb6834eec1303573/ngx_http_proxy_connect_module.c#L1535

This name is used for debugging, not for resolving the upstream server address. 

https://github.com/chobits/ngx_http_proxy_connect_module/blob/cb4dcd53310afa481449808afb6834eec1303573/ngx_http_proxy_connect_module.c#L1540

`u->resolved->host` is used for resolving upstream server address.

---


> It will be very good to be able to change sni name just as we are able to change connect address with proxy_connect_address

And also note that this module will not add/change backend address/hostname/sni name to raw data under CONNECT tunnel, it's only used to be destination address of TCP connection with upstream server.

Theoretically, the raw data under CONNECT tunnel can be any protocol. 
Although the raw data under CONNECT tunnel is SSL stream, proxy server still cannot decrypt and change SNI name of the SSL stream. That normal L7 proxy (like nginx) can proxy SNI name is because L7 proxy has SSL certificate/key.

This module is only used to create the CONNECT tunnel and proxy raw data under this tunnel, it does not modify any data under this tunnel.

**Comment by chobits** [comment]
> Although the raw data under CONNECT tunnel is SSL stream, proxy server still cannot decrypt and change SNI name of the SSL stream. That normal L7 proxy (like nginx) can proxy SNI name is because L7 proxy has SSL certificate/key.
( I'm not SSL expert, not confirm whether proxy can modify SNI in CLIENTHELLO message without SSL cert/key, only confirm that proxy cannot modify data flow under ssl stream without SSL cert/key. )

I have consulted a SSL expert, he told me that proxy cannot modify SNI name of original data flow without SSL cert/key, because at the end of  SSL handshake, the hash of all handshake interaction information will be verified.

**Comment by deba12** [comment]
Thanks
