### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by Andarius** [chobits/ngx_http_proxy_connect_module#209]
Hi,

I'm sorry if this question is a bit off-topic but I was wondering if it was possible to use NGINX rate limiting features when using this module ?
Let's say I want to limit the requests I make to an API using NGINX as proxy ?

**Comment by chobits** [comment]
I think it is hard to do request limiting over this module.

If u used this module, nginx would not know the proxied data flow. The proxied data flow becomes black box. This module can only transfer data flow , it can not extract the internal data because of [the feature of HTTPS tunnel](https://github.com/chobits/ngx_http_proxy_connect_module/issues/81#issuecomment-469099895).

**Comment by chobits** [comment]
Also note that, the connection (I mean TCP connection of HTTPS tunnel) can be limited if someone secondary development of this module.

**Comment by Andarius** [comment]
Thanks for the answer !
