### ISSUE TITLE
Can this module be used without the client need to set proxy configuration on browsers?

### ISSUE THREAD

**Issue by Artin70** [chobits/ngx_http_proxy_connect_module#258]
Hi

Thanks for dveloping this great module and sorry for such an amatuer question.

I've successfuly implemented this module and get http 200 response when I use curl on my client (windows CMD or the proxy erver).
Is there anyway to use this proxy on browsers or third-party apps without the need of configuring proxy for them? something like non-Connect nginx http forward proxy which can be used as a url like this:

`<proxy server address or IP>:<proxy port>/<[proxy_connect_address]>` 

I can't access the disired address when trying it like this.

Thanks in advance.

**Comment by chobits** [comment]
>   Is there anyway to use this proxy on browsers or third-party apps without the need of configuring proxy for them?

Its unable to do this. 

In order to activate the tunnel, communication is necessary between the client and server. The client must send a CONNECT request to the server to ask it to open the tunnel. If you haven't configured the client with the CONNECT proxying setting, it will not automatically send a CONNECT request to indicate that it wants to use the CONNECT tunnel.

**Comment by chobits** [comment]
If you're looking for information on how to configure your browser to use an HTTPS proxy, you can check out this link for guidance: https://github.com/chobits/ngx_http_proxy_connect_module/issues/22#issuecomment-346941271

**Comment by chobits** [comment]
I am closing this issue. Please feel free to reopen it if you have any further questions.
