### ISSUE TITLE
目前支持 openresty上吗？ //EN: Does it support openresty?

### ISSUE THREAD

**Issue by yinjun622** [chobits/ngx_http_proxy_connect_module#26]

**Comment by chobits** [comment]
可以的。openresty是标准的nginx，所以没啥问题。

不过我没有专门测过，如果patch打上去没啥问题就ok了

**Comment by chobits** [comment]
有空我测下patch和openresty的兼容性（考虑到openresty也打了很多patch，可能会导致我这个patch打的位置冲突，不过概率较小）

**Comment by yinjun622** [comment]
@chobits 

proxy_connect.patch
patching file src/http/ngx_http_core_module.c
Hunk #1 succeeded at 913 (offset 22 lines).
Hunk #2 succeeded at 951 (offset 22 lines).
Hunk #3 succeeded at 1233 with fuzz 2 (offset 61 lines).
patching file src/http/ngx_http_core_module.h
Hunk #1 succeeded at 315 with fuzz 1 (offset -28 lines).
patching file src/http/ngx_http_parse.c
patching file src/http/ngx_http_request.c
Hunk #1 succeeded at 995 (offset 27 lines).
Hunk #2 succeeded at 1613 (offset 40 lines).
Hunk #3 succeeded at 1938 (offset 40 lines).
patching file src/http/ngx_http_request.h
Hunk #2 succeeded at 412 (offset 8 lines).
patching file src/http/ngx_http_variables.c
Hunk #1 succeeded at 161 (offset 9 lines).

安装上后，执行https代理，不行

**Comment by chobits** [comment]
> 安装上后，执行https代理，不行

提供一下openresty相关配置，以及客户端使用方式

**Comment by yinjun622** [comment]
> 提供一下openresty相关配置，以及客户端使用方式

下面是我的安装方式
`cd ~/openresty-1.13.6.1/bundle/nginx-1.13.6
patch -p1 < ${APPS_PATH}/ngx_http_proxy_connect_module/proxy_connect.patch
./configure --prefix=/opt/openresty \
            --with-luajit \
           --add-module=${APPS_PATH}/ngx_http_proxy_connect_module `

nginx配置与文档上相同，
客户端配置使用chrome代理
<img width="914" alt="screen shot 2018-02-02 at 23 56 13" src="https://user-images.githubusercontent.com/988571/35742299-fe2dfaea-0874-11e8-8c86-1c3e404b5af4.png">

**Comment by chobits** [comment]
hi @yinjun622 

目前无法使用在 nginx-1.13+ 版本上，由于nginx core在1.13上对phase处理阶段做了变更，导致patch打上去位置不对。所以暂时还不支持。

TODO见：https://github.com/chobits/ngx_http_proxy_connect_module/issues/12

**Comment by chobits** [comment]
hi , I have released new patch for nginx-1.13.x~nginx-1.14.x

* for details how to install this module, see https://github.com/chobits/ngx_http_proxy_connect_module/#install

* you should select right patch before installing

---

Install
=======

* Select right patch for building:


| nginx version | enable REWRITE phase | patch |
| --: | --: | --: |
| 1.4.x ~ 1.12.x  | NO  | [proxy_connect.patch](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect.patch) |
| 1.4.x ~ 1.12.x  | YES | [proxy_connect_rewrite.patch](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite.patch) |
| 1.13.x ~ 1.14.x | NO  | [proxy_connect_1014.patch](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_1014.patch)|
| 1.13.x ~ 1.14.x | YES | [proxy_connect_rewrite_1014.patch](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_1014.patch) |

This module disables nginx REWRITE phase for CONNECT request by default, which means `if`, `set`, `rewrite_by_lua` and other REWRITE phase directives cannot be used. To enable these, you should use `proxy_connect_rewrite.patch` instead of `proxy_connect.patch`. (`TODO`: merge two patches into one.)

* Install this module from source:

```
$ wget http://nginx.org/download/nginx-1.9.2.tar.gz
$ tar -xzvf nginx-1.9.2.tar.gz
$ cd nginx-1.9.2/
$ patch -p1 < /path/to/ngx_http_proxy_connect_module/patch/proxy_connect.patch
$ ./configure --add-module=/path/to/ngx_http_proxy_connect_module
$ make && make install
```

**Comment by ipyleaf** [comment]
openresty-1.13.6.1，出现unknown directive "proxy_connect"的报错，当启动nginx的时候。试了1.9以上的openresty，都有同样的问题。

**Comment by ipyleaf** [comment]
./configure --add-module=/home/aa/downloads/ngx_http_proxy_connect_module-master

**Comment by chobits** [comment]
hi @ipyleaf , 让我看下。最近会将对openresty的兼容性完整测试一下，文档会单独加入 `#OpenResty-Compatibility` 列表

**Comment by chobits** [comment]
hi @ipyleaf 我这边测试没有问题，如下我的测试方法：


```
$ wget https://openresty.org/download/openresty-1.13.6.2.tar.gz
$ tar xvf openresty-1.13.6.2.tar.gz

$ cd openresty-1.13.6.2
$ patch -d bundle/nginx-1.13.6/ -p 1 < /path/to/ngx_http_proxy_connect_module/patch/proxy_connect_1014.patch
$ ./configure --add-module=/path/to/ngx_http_proxy_connect_module --prefix=$(pwd)/output
$ make -j8
$ make install

$ cd output/nginx/
$ vim conf/nginx.conf           # << modify nginx.conf for proxy_connect module
$ sbin/nginx -t                 # check nginx.conf
```

**Comment by chobits** [comment]
think it resolved

**Comment by trockxi** [comment]
cd /opt/soft/openresty-1.17.8.2
./configure --prefix=/opt/soft/openresty --with-http_v2_module --with-http_sub_module --with-http_stub_status_module --with-luajit --add-module=/opt/soft/ngx_http_proxy_connect_module
patch -d build/nginx-1.17.8/ -p 1 < /opt/soft/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_101504.patch

    server {
        listen 8000;
        # dns resolver used by forward proxying
        resolver 223.5.5.5;
        # forward proxy for CONNECT request
        proxy_connect;
        proxy_connect_allow            443 563;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;
        # forward proxy for non-CONNECT request
        location / {
            proxy_pass http://$host;
            proxy_set_header Host $host;
        }
     }
2020/11/03 12:10:42 [emerg] 4439#0: unknown directive "proxy_connect" in /opt/soft/openresty/nginx/conf/nginx.conf:424

help
