### ISSUE TITLE
Tuneling SSH over HTTP - 502 Bad Gateway

### ISSUE THREAD

**Issue by archenroot** [chobits/ngx_http_proxy_connect_module#3]
For SSH tunneling I am using default config as you proposed, except I do:
`proxy_connect_allow 22;`

When configured SSH config with following config:
ProxyCommand /usr/bin/proxytunnel -p public-address:80 -d remote-host:22 -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)"

When I used nginx streams it works, but with streams I am limited to just SSH and cannot use locations with http web sites. I want to mix this by using this plugin.

The web site with proxy_pass works fine, but I cannot connect to SSH:
HTTP return code: 502 Bad Gateway

It even reports for some few seconds on execution in terminal:
Via public-address:80 -> remote-address-behing-proxy:22

Any idea?

**Comment by chobits** [comment]
hi @archenroot 

I know that proxytunnel will send CONNECT method to `public-address:80`, as following

```
CONNECT remote-host:22 HTTP/1.0
Proxy-Connection: Keep-Alive
```

If `public-address:80` is listend by nginx+ngx_http_proxy_connect_module, ngx_http_proxy_connect_module will connect `remote-host:22` with TCP connection (note that there is no SSL layer over this connection). After establishing connection with `remote-host:22`, it will proxy data between `proxytunnel` with `remote-host:22`.

So the topology is as following:

```
(client) -> ssh-proxycommand -> proxytunnel -> nginx+ngx_http_proxy_connect (listen 80) --> remote-host:22
```

I dont understand your problem really. What is `(client)`?   Is it `ssh` command?

> When I used nginx streams it works, but with streams I am limited to just SSH and cannot use locations with http web sites. I want to mix this by using this plugin.

Can you show your ngx-stream configure?

Note that ngx_http_proxy_connect_module cannot use locations also, because there is no location information in CONNECT request, only `<remote-host>` and `<remote-port>` included, that's why `proxy_connect` command only supports `server {}` context.

**Comment by chobits** [comment]
Think it resolved.
Reopen this issue if you have any quetions.
