### ISSUE TITLE
Installing module on newer version of nginx

### ISSUE THREAD

**Issue by ruediheimlicher** [chobits/ngx_http_proxy_connect_module#37]
Hi
I have installed a reverse proxy with nginx with https on a Raspberry Pi Z with rasbian Stretch to connect my home central and it works well. Now I would like to install the above module, but I have version  nginx/1.10.3 installed. Folowing the install code provided installes nginx 1.9.2.
How can I apply the patch to the newer version?
Thanks in advance
Ruedi

**Comment by chobits** [comment]
The patch supports only up to nginx-1.12.x.

I'll update this patch to nginx-1.13.x in ~1-2 weeks.

**Comment by kiela** [comment]
@chobits Great work on this forward proxy module! Is there any chance it will be updated to support 1.13.x?

**Comment by chobits** [comment]
@kiela 

yeah, I haved updated this module to 1.13.x already. After strict testing, I will soon update this repo.

**Comment by chobits** [comment]
hi , I have released new patch for nginx-1.13.x~nginx-1.14.x

* for details how to install this module, see https://github.com/chobits/ngx_http_proxy_connect_module/#install

* you should select right patch before installing

Install
=======

* Select right patch for building:

| nginx version | enable REWRITE phase | patch |
| --: | --: | --: |
| 1.4.x ~ 1.12.x  | NO  | [proxy_connect.patch](patch/proxy_connect.patch) |
| 1.4.x ~ 1.12.x  | YES | [proxy_connect_rewrite.patch](patch/proxy_connect_rewrite.patch) |
| 1.13.x ~ 1.14.x | NO  | [proxy_connect_1014.patch](patch/proxy_connect_1014.patch) |
| 1.13.x ~ 1.14.x | YES | [proxy_connect_1014_rewrite.patch](patch/proxy_connect_1014_rewrite.patch) |

`proxy_connect.patch` includes logic in macro NGX_HTTP_RPOXY_CONNECT, and [config](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/config#L5) script will enable this macro automatically.

This module disables nginx REWRITE phase for CONNECT request by default, which means `if`, `set`, `rewrite_by_lua` and other REWRITE phase directives cannot be used. To enable these, you should use `proxy_connect_rewrite.patch` instead of `proxy_connect.patch`. (`TODO`: merge two patches into one.)

* Install this module from source:

```
$ wget http://nginx.org/download/nginx-1.9.2.tar.gz
$ tar -xzvf nginx-1.9.2.tar.gz
$ cd nginx-1.9.2/
$ patch -p1 < /path/to/ngx_http_proxy_connect_module/proxy_connect.patch
$ ./configure --add-module=/path/to/ngx_http_proxy_connect_module
$ make && make install
```

**Comment by Gondost** [comment]
@chobits 

Can this be dynamically built now and loaded, or does it still require being built from the full source?

**Comment by chobits** [comment]
hi @Gondost 

It requires being built from the full source, because this module need to patch nginx core.

**Comment by chobits** [comment]
Think it resolved.  For more details, see https://github.com/chobits/ngx_http_proxy_connect_module/issues/37#issuecomment-382679911.

Leave a message on this issue if you have a similar problem.
